### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by mgrddsj** [bunnyblueair/DroidNCM#1]
求更新:disappointed_relieved:

**Comment by bunnyblueair** [comment]
@mgrddsj 更新啥？

**Comment by mgrddsj** [comment]
没事了，很久之前的issue，我close了吧

**Comment by mgrddsj** [comment]
不好意思，当年年少无知，而且当时不会自己编译（当时没有 Release），开了这个 issue。现在看着都尴尬。能否麻烦把这个 issue 彻底删除？谢谢！
[删除方法](https://help.github.com/cn/github/managing-your-work-on-github/deleting-an-issue)
