### ISSUE TITLE
这两首无法转换- -跪求修复

### ISSUE THREAD

**Issue by BurningBit124** [bunnyblueair/DroidNCM#10]
![Screenshot_20190721_192735](https://user-images.githubusercontent.com/53142364/61590553-c8878900-ab80-11e9-82e4-bd84bae26b2a.jpg)

**Comment by BurningBit124** [comment]
链接附上- -
http://music.163.com/song/27678004/?userid=436986601 http://music.163.com/song/1338149091/?userid=436986601

**Comment by bunnyblueair** [comment]
收到

**Comment by bunnyblueair** [comment]
使用2.1.0版本
