### ISSUE TITLE
sort in ncm list

### ISSUE THREAD

**Issue by luvletter2333** [bunnyblueair/DroidNCM#18]
It's too difficult to find the music i want and would you please add a switch to toggle showing ncm path?

**Comment by luvletter2333** [comment]
it seems that it sort in date asc. But if i convert a newer file in the bottom of the list, it will jump to the top of the list.

**Comment by luvletter2333** [comment]
i think there are some functional improvements:
 - Add a sort button and it can sort by name asc/desc or date asc/desc.
- Hold the position when finishing converting.
- Add a button to toggle showing file path

**Comment by bunnyblueair** [comment]
fixed https://github.com/bunnyblueair/DroidNCM/releases
