### ISSUE TITLE
无法批量转换

### ISSUE THREAD

**Issue by Zhouzerong233** [bunnyblueair/DroidNCM#22]
您好，在以下两台手机中无法进行批量转换，转换完一首歌后软件出现闪退，但是那一首歌已经转换好了，以下是手机信息

vivo x6s

![vivox6s](https://s1.ax1x.com/2020/04/11/GHzY1f.md.png)

华为畅享8e

![atu-al10](https://s1.ax1x.com/2020/04/11/GHz63V.jpg)

**Comment by bunnyblueair** [comment]
1 单首是否能够转换成功？
2 用的什么版本
3 不能转换的歌曲是啥

**Comment by Zhouzerong233** [comment]
- 单曲可以成功转换

- 使用的是3.0

- 很多，反正就是不能批量转换，单曲都可以

**Comment by bunnyblueair** [comment]
请提供具体信息
