### ISSUE TITLE
转换后音乐名称改变

### ISSUE THREAD

**Issue by Gluneklairo** [bunnyblueair/DroidNCM#23]
转换后会丢失空格，丢失歌手名之间的空格和“-”前后的空格，强迫症需要自己重命名改正

**Comment by bunnyblueair** [comment]
fixed it later

**Comment by Gluneklairo** [comment]
Have you finished the fixing? Please upload your new build, I want to use it. 😁

**Comment by bunnyblueair** [comment]
I will upload it today

**Comment by Gluneklairo** [comment]
I really appreciate it. 😀On Aug 17, 2020 10:09, BunnyBlue <notifications@github.com> wrote:
I will upload it today

**Comment by bunnyblueair** [comment]
install last release

**Comment by Gluneklairo** [comment]
两个歌手间的空格还是没有😅

**Comment by Gluneklairo** [comment]
现在网易云两个歌手之间改为逗号了，但是这个app还是把逗号删掉了

**Comment by Gluneklairo** [comment]
检查了一遍，原来所有符号都被清除了

**Comment by bunnyblueair** [comment]
show me music id

**Comment by Gluneklairo** [comment]
Gabrielle Aplin,Nina Nesbitt - Miss You 2.ncm转换后变成Gabrielle AplinNina Nesbitt - Miss You 2.flac,两个歌手之间的逗号没了

发送自 Windows 10 版邮件应用

发件人: BunnyBlue
发送时间: 2020年8月19日 18:39
收件人: bunnyblueair/DroidNCM
抄送: Gluneklairo; Author
主题: Re: [bunnyblueair/DroidNCM] 转换后音乐名称改变 (#23)

show me music id

**Comment by bunnyblueair** [comment]
try this https://github.com/bunnyblueair/DroidNCM/releases/tag/v3.2

**Comment by Gluneklairo** [comment]
![IMG_20200827_175229](https://user-images.githubusercontent.com/65527723/91425759-27442980-e88e-11ea-97d1-04fef5a3526c.jpg)
好像还是没有解决

**Comment by bunnyblueair** [comment]
> ![IMG_20200827_175229](https://user-images.githubusercontent.com/65527723/91425759-27442980-e88e-11ea-97d1-04fef5a3526c.jpg)
> 好像还是没有解决

用的是3.2版本碼？

**Comment by Gluneklairo** [comment]
是的On Aug 27, 2020 18:36, BunnyBlue <notifications@github.com> wrote:





好像还是没有解决



用的是3.2版本碼？
