### ISSUE TITLE
一加7Pro 氢OS 转换闪退

### ISSUE THREAD

**Issue by evanxyf** [bunnyblueair/DroidNCM#4]
直接使用1.0.0版本的npk安装，刚安装那时候可以转换，手机用了一段时间后再次转换时app闪退了，不清楚是否需要提供log且不知如何提取log

**Comment by evanxyf** [comment]
npk->apk

**Comment by bunnyblueair** [comment]
有adb没？adb logcat看下，顺便说下OS版本

**Comment by bunnyblueair** [comment]
用这个 https://github.com/bunnyblueair/DroidNCM/releases/tag/2.0.0 有问题在open
