### ISSUE TITLE
小米6X闪退，系统Android9.0，MIUI10

### ISSUE THREAD

**Issue by C1048576** [bunnyblueair/DroidNCM#5]
小米6X闪退，系统Android9.0，MIUI10，扫描文件，点全部转换，点击确认转换的对话框后转了一圈就闪退了，文件没有被转换，即使是一个文件也不能转换

**Comment by bunnyblueair** [comment]
请提供崩溃的ncm文件，或者对应的歌名

**Comment by bunnyblueair** [comment]
用这个 https://github.com/bunnyblueair/DroidNCM/releases/tag/2.0.0 有问题在open
