### ISSUE TITLE
最新版一加3 氢OS无法转换

### ISSUE THREAD

**Issue by davidelectricfree** [bunnyblueair/DroidNCM#6]
安卓8.0.0
安装1.2.0软件无法打开，点击就闪退。
安装1.2.1软件可以正常打开及扫描，但是点击转换以后，大概0.5s后转换的图标消失，也不提示转换成功也不提示转换失败。到同级目录查看，并没有转换成功的文件。

**Comment by davidelectricfree** [comment]
另外，歌名的话中文英文日文歌好像都不成功

**Comment by bunnyblueair** [comment]
文件存在在/sdcard/Music下面 你看下

**Comment by bunnyblueair** [comment]
用这个 https://github.com/bunnyblueair/DroidNCM/releases/tag/2.0.0 有问题在open
